# A Quick Blitz on PyTorch tensor operations

PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing.

The torch package contains data structures for multi-dimensional tensors and mathematical operation over these are defined. Additionally, it provides many utilities for efficient serializing of Tensors and arbitrary types, and other useful utilities.

In this notebook, I am going to enlighten following five fuctions with suitable examples:

1. torch.arange()
> initalizes a tensor with a range of value
2. torch.complex()
> constructs a complex tensor with real and imaginary part
3. torch.squeeze()
> returns a tensor with all the dimensions of `input` size 1 removed
4. torch.as_strided()
> creates a view of an existing *torch.Tensor* `input`
5. torch.randn()
> returns a tensor defined by the variable argument size, containing random numbers from standard normal distribution.

Before we begin, let's install and import PyTorch.

In [1]:
import torch

------------------------------------------------------------------------------------------------------
## Function 1 - torch.arange

>torch.arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

This funtion returns a 1-D tensor of size `{(end-start)/step}` with values from the interval `[start, end)` taken with common difference `step` beginning from *start*.

In [2]:
# Example 1 - working

torch.arange(8)

tensor([0, 1, 2, 3, 4, 5, 6, 7])

This example clearly shows, if only one parameter is passed through the function then that parameter will be considered as `end`. This implies `start` will be taken as 0 and `step` will be 1, by default.

In [3]:
# Example 2 - working

torch.arange(2, 5.5, 0.45)

tensor([2.0000, 2.4500, 2.9000, 3.3500, 3.8000, 4.2500, 4.7000, 5.1500])

If dtype is not given, infer the data type from the other input arguments. If any of start, end, or stop are floating-point, the dtype is inferred to be the default dtype. Otherwise, the dtype is inferred to be torch.int64.

In [4]:
# Example 3 - breaking (to illustrate when it breaks)

torch.arange(8, 2.5, 2)

RuntimeError: upper bound and larger bound inconsistent with step sign

Note that if the `start` is greater than the `end`, then `step` can't be positive.
To fix this, you need to set the `step` as a negative number in order to traverse back.

`torch.arange()` can be used whenever there is a need to create a 1-D tensor with a specified range and step.

------------------------------------------------------------------------------------------------------
## Function 2 - torch.complex

> torch.complex(real, imag, *, out=None) → Tensor

Constructs a complex tensor with its real part equal to `real` and its imaginary part equal to `imag`.

In [5]:
# Example 1 - working

real1 = torch.tensor([1, 1], dtype = torch.float32)
imag1 = torch.tensor([2, 3], dtype = torch.float32)

z = torch.complex(real1, imag1)
z

tensor([1.+2.j, 1.+3.j])

The elements of `real1` tensor forms a complex tensor with the corresponding elements of `imag1` tensor.

In [6]:
# Example 2 - working

real2 = torch.tensor([[1, 2],
                      [3, 4]], dtype = torch.float32)
imag2 = torch.tensor([[3, 4],
                      [5, 6]], dtype = torch.float32)

z2 = torch.complex(real2, imag2)
z2

tensor([[1.+3.j, 2.+4.j],
        [3.+5.j, 4.+6.j]])

`torch.complex` also works for multi-dimensional tensors having same shape.

In [7]:
# Example 3 - breaking (to illustrate when it breaks)

real3 = torch.tensor([[1, 2],
                     [3, 4]])
imag3 = torch.tensor([[6, 7],
                    [8, 9]])

z3 = torch.complex(real3, imag3)
z3

RuntimeError: Expected both inputs to be Float or Double tensors but got Long and Long

`torch.complex(real, imag)` only accepts float or double datatype values. If we do not specify the `dtype` while creating a tensor then it will accept `long` as the datatype. Hence, using `torch.complex` on that tensor will give the RunTime Error.

This function can be used when we need to create a complexed tensor. 

------------------------------------------------------------------------------------------------------
## Function 3 - torch.squeeze

>torch.squeeze(input, dim=None, *, out=None) → Tensor

Returns a tensor with all the dimensions of input of size 1 removed.

In [8]:
# Example 1 - working

t = torch.tensor([[1, 1, 1, 1],
                 [2, 2, 2, 2],
                 [3, 3, 3, 3]], dtype = torch.float32)

print(t.reshape(1, 12))
print(t.reshape(1, 12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [9]:
t2 = t.reshape(1, 12).squeeze()
print(t2)
print(t2.shape)
print(t2.squeeze().unsqueeze(dim = 0).shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])
torch.Size([1, 12])


Squeezing a tensor removes all of the axes that have a length of 1. Also unsqueezing a tensor adds a dimension with a length of 1. These functions allow us to expand or shrink the rank of our tensor.

In [10]:
# Example 2 - working

t3 = torch.zeros(2, 1, 2, 1, 3)
t3.size()

torch.Size([2, 1, 2, 1, 3])

In [11]:
print(torch.squeeze(t3).size())
print(torch.squeeze(t3, 0).size())
print(torch.squeeze(t3, 1).size())
print(torch.squeeze(t3, 2).size())
print(torch.squeeze(t3, 3).size())
print(torch.squeeze(t3, 4).size())

torch.Size([2, 2, 3])
torch.Size([2, 1, 2, 1, 3])
torch.Size([2, 2, 1, 3])
torch.Size([2, 1, 2, 1, 3])
torch.Size([2, 1, 2, 3])
torch.Size([2, 1, 2, 1, 3])


This example shows squeezing of the tensor with given dimension. It can be seen that squeezing only works for shrinking 1 dimension, it does not have any effect on others in the given tensor.

In [12]:
# Example 3 - breaking (to illustrate when it breaks)

t4 = torch.tensor([1, 5, 3], dtype = torch.float32)
print(t4.shape)
print(t4.squeeze().unsqueeze().shape)

torch.Size([3])


TypeError: unsqueeze() missing 1 required positional arguments: "dim"

Unsqueezing always requires dimension as an argument `dim`.

If the tensor has a batch dimension of size 1, then `squeeze(input)` will also remove the batch dimension, which can lead to unexpected errors.

This function can be used when there is a need to shrink or expand the rank of a tensor.

------------------------------------------------------------------------------------------------------
## Function 4 - torch.as_strided

>torch.as_strided(input, size, stride, storage_offset=0) → Tensor

Create a view of an existing *torch.Tensor* `input` with specified `size`, `stride` and `storage_offset`.

In [13]:
# Example 1 - working

t1 = torch.tensor([[5, 3],
                   [6, 4],
                   [7, 8]], dtype = torch.float32)

t2 = torch.as_strided(t1,(2,2),(2,1))
t2

tensor([[5., 3.],
        [6., 4.]])

In the above example, we are creating a view of size (2,2) out of (3,2) tensor by using the stride value (2,1).
For the first dimension, every 2nd value from the `start` will be picked and for the 2nd dimension, every 1st value from the already picked 1st dimension will be picked.

In [14]:
# Example 2 - working

x = torch.randn(3, 3)
print(x)

y = torch.as_strided(x,(3,2),(2,3))
y

tensor([[ 0.5939, -1.6919,  0.9064],
        [-1.5749,  0.8807, -0.3661],
        [ 1.4907,  0.9837,  1.0228]])


tensor([[ 0.5939, -1.5749],
        [ 0.9064, -0.3661],
        [ 0.8807,  0.9837]])

Here, we are creating a view of size (3,2) out of (3,3) tensor by using the stride value (2,3).
For the first dimension, every 2nd value from the `start` will be picked and for the 2nd dimension, every 3rd value from the already picked 1st dimension will be picked.

In [15]:
# Example 3 - breaking (to illustrate when it breaks)

x = torch.randn(3, 3)
print(x)

y = torch.as_strided(x,(3,2),(2,6))
y

tensor([[ 0.7991, -1.3464, -0.0839],
        [ 0.5485, -0.2519, -0.9006],
        [-0.7210, -1.7063, -1.4901]])


RuntimeError: setStorage: sizes [3, 2], strides [2, 6], storage offset 0, and itemsize 4 requiring a storage size of 44 are out of bounds for storage of size 36

As we are striding through the 1st dimension `3` and the 2nd dimension `2` of the output matrix, their product `3x2=6`, cannot be less than the sum of stride indices `2+6=8`. This means we cannot make long skips such that we exceed the last element of the original tensor.

This function is useful in directly accessing a specific set of values in a tensor based on the storage memory format for direct elementary operations with more efficiency.

------------------------------------------------------------------------------------------------------
## Function 5 - torch.randn()

> torch.randn(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

PyTorch torch.randn() returns a tensor defined by the variable argument size (sequence of integers defining the shape of the output tensor), containing random numbers from standard normal distribution.

In [16]:
# Example 1 - working

t1 = torch.tensor([[1, 2, 3],
                 [5, 6, 7],
                 [8, 6, 4]], dtype = torch.float32)
t2 = torch.randn(t1.shape)
t1, t2

(tensor([[1., 2., 3.],
         [5., 6., 7.],
         [8., 6., 4.]]),
 tensor([[ 1.1783, -0.0732,  0.2186],
         [ 0.0207,  0.0675,  0.4593],
         [-0.5369, -0.4181, -1.4149]]))

This returns a tensor of size of the tensor x, filled with values from standard normal distribution, i.e mean is 0 and variance is 1.

In [17]:
# Example 2 - working

t2 = torch.randn(2, 3, 4, requires_grad = True)
t2

tensor([[[ 0.6480, -1.7293, -0.3584,  0.2468],
         [ 0.0075, -0.7489, -0.7530, -0.4006],
         [-0.4935,  0.1592, -0.1691,  1.8577]],

        [[-2.7374,  0.0997,  0.0680, -0.1719],
         [-0.0843,  0.2185,  0.3678, -1.6001],
         [-0.7214,  1.1170, -0.3394, -0.8283]]], requires_grad=True)

This returns a tensor of size `2x3x4`, filled with random numbers, also recording the gradient values, when performed. 

In [18]:
# Example 3 - breaking (to illustrate when it breaks)

t3 = torch.randn(2., 3., 4., requires_grad = True)
t3

TypeError: randn() received an invalid combination of arguments - got (float, float, float, requires_grad=bool), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


This error is generated because `size` parameter cannot accept floating point value.

The `randn()` function is useful for selecting weights as a starting point when beginning to train a predictive program.

------------------------------------------------------------------------------------------------------
## Conclusion

In this notebook, I tried to explain just 5 different PyTorch tensor operations. Each of these has unique paramaters and methods that allow users to play around with data and deriving insights.
Having now completed this assignment, and spent significant time looking at the subtle differences in these functions it is my conclusion that Pytorch is a valuable tool for Deep Learning.

## Reference Links

* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html

In [19]:
!pip install jovian --upgrade --quiet

In [20]:
import jovian

<IPython.core.display.Javascript object>

In [21]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "priyanshu-kr/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/priyanshu-kr/01-tensor-operations


'https://jovian.ai/priyanshu-kr/01-tensor-operations'