# PyTorch Basics: Tensors and Gradients

In [1]:
!pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 159.4 MB 4.8 kB/s eta 0:00:01    |█████▎                          | 26.2 MB 826 kB/s eta 0:02:42     |████████████████████▊           | 103.2 MB 4.0 MB/s eta 0:00:15     |█████████████████████████       | 124.8 MB 161 kB/s eta 0:03:34     |█████████████████████████▏      | 125.2 MB 3.3 MB/s eta 0:00:11     |███████████████████████████████▉| 158.4 MB 3.2 MB/s eta 0:00:01
     |████████████████████████████████| 11.8 MB 3.2 MB/s eta 0:00:01    |██████████████████▊             | 6.9 MB 2.3 MB/s eta 0:00:03
     |████████████████████████████████| 7.6 MB 102 kB/s eta 0:00:01     |████████████████████████████▉   | 6.9 MB 267 kB/s eta 0:00:03


In [1]:
import torch

## Tensors

At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional array.

In [14]:
t1 = torch.tensor(4.)
t1

tensor(4.)

4. means 4.0 (floating point number)

In [15]:
t1.dtype

torch.float32

In [16]:
t2 = torch.tensor([1. ,2 ,3])
t2

tensor([1., 2., 3.])

In [17]:
t3 = torch.tensor([[1, 2],
                 [3, 4.],
                 [5., 6]])
t3

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [18]:
# 3d array

t4 = torch.tensor([
    [[1, 2, 3],
    [4, 5, 6]],
    [[7, 8, 9],
    [10, 11, 12]]])
t4

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

Tensors can have any number of dimensions, and different lengths along each dimension.

In [19]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [20]:
print(t3)
t3.shape

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


torch.Size([3, 2])

In [21]:
print(t2)
t2.shape

tensor([1., 2., 3.])


torch.Size([3])

In [22]:
print(t4)
t4.shape

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


torch.Size([2, 2, 3])

## Tensor operations and gradients

In [23]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad = True)

x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [24]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, y is a tensor with the value 3 * 4 + 5 = 17. What makes PyTorch special is that we can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b. To compute the derivatives, we can call the .backward method on our result y.

In [25]:
# compute derivative
y.backward()

The derivatives of y w.r.t. the input tensors are stored in the .grad property of the respective tensors.

In [26]:
# Display gradients
print('dy/dw:', w.grad)
print('dy/dx:', x.grad)
print('dy/db:', b.grad)

dy/dw: tensor(3.)
dy/dx: None
dy/db: tensor(1.)


As expected, dy/dw has the same value as x, i.e., 3, and dy/db has the value 1. Note that x.grad is None because x doesn't have requires_grad set to True.

The "grad" in w.grad is short for gradient, which is another term for derivative. The term gradient is primarily used while dealing with vectors and matrices.

#### Note: A matrix is a special type of tensor but a tensor need not to be a matrix always. Tensor can be a vector, a number, a 3D array with regular shape.

## Tensor Fuctions

Apart from arithmetic operations, the torch module also contains many functions for creating and manipulating tensors.

In [13]:
t6 = torch.full((3, 2), 34)
t6

tensor([[34, 34],
        [34, 34],
        [34, 34]])

In [29]:
# to concatenate two tensors, they must have same dimensions
t7 = torch.cat((t3, t6))
t7

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [34., 34.],
        [34., 34.],
        [34., 34.]])

In [31]:
t8 = torch.sin(t7)
t8

tensor([[ 0.8415,  0.9093],
        [ 0.1411, -0.7568],
        [-0.9589, -0.2794],
        [ 0.5291,  0.5291],
        [ 0.5291,  0.5291],
        [ 0.5291,  0.5291]])

In [36]:
t9 = torch.cos(t7)
t9

tensor([[ 0.5403, -0.4161],
        [-0.9900, -0.6536],
        [ 0.2837,  0.9602],
        [-0.8486, -0.8486],
        [-0.8486, -0.8486],
        [-0.8486, -0.8486]])

In [38]:
t10 = torch.tan(t7)
t10

tensor([[ 1.5574, -2.1850],
        [-0.1425,  1.1578],
        [-3.3805, -0.2910],
        [-0.6235, -0.6235],
        [-0.6235, -0.6235],
        [-0.6235, -0.6235]])

In [39]:
t11 = t10.reshape(3, 2, 2)
t11

tensor([[[ 1.5574, -2.1850],
         [-0.1425,  1.1578]],

        [[-3.3805, -0.2910],
         [-0.6235, -0.6235]],

        [[-0.6235, -0.6235],
         [-0.6235, -0.6235]]])

https://pytorch.org/docs/stable/torch.html

## Interoperability with NumPy

Numpy is a popular open-source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays and has a vast ecosystem of supporting libraries, including:

    Pandas for file I/O and data analysis
    Matplotlib for plotting and visualization
    OpenCV for image and video processing

If you're interested in learning more about Numpy and other data science libraries in Python, check out this tutorial series: https://jovian.ai/aakashns/python-numerical-computing-with-numpy .

Instead of reinventing the wheel, PyTorch interoperates well with Numpy to leverage its existing ecosystem of tools and libraries.

In [3]:
import numpy as np

In [4]:
x = np.array([[1, 2], [4, 5.]])
x

array([[1., 2.],
       [4., 5.]])

We can convert a NumPy array to a PyTorch tensor using torch.from_numpy.

In [5]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [4., 5.]], dtype=torch.float64)

In [7]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

We can convert a PyTorch tensor to a Numpy array using the .numpy method of a tensor.

In [10]:
z = y.numpy()
z

array([[1., 2.],
       [4., 5.]])

In [11]:
z.dtype

dtype('float64')

The interoperability between PyTorch and Numpy is essential because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.

You might wonder why we need a library like PyTorch at all since Numpy already provides data structures and utilities for working with multi-dimensional numeric data. There are two main reasons:

Autograd: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.

GPU support: While working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a Graphics Processing Unit (GPU). Computations that might typically take hours can be completed within minutes using GPUs.
